#!/usr/bin/env python3
"""
Generate an idempotent SQL import script from parsed-products.json.

Output: supabase/migrations/006_full_pricelist_import.sql
- Inserts products that don't already exist (matched by brand + name)
- Inserts SKUs for each product (skipping size_ml combos that already exist)
- Stock defaults to 1 (per user request: "set stock > 0 for ex 1")
- Wrapped in a transaction
"""

import json
import sys
import uuid
import re

JSON_PATH = "scripts/parsed-products.json"
OUT_PATH = "supabase/migrations/006_full_pricelist_import.sql"


def label_for(size_ml):
    """Match the labeling convention used in 005_price_list_import.sql."""
    if size_ml <= 5:
        return f"{size_ml}ml Mostră"
    if size_ml <= 15:
        return f"{size_ml}ml Călătorie"
    return f"{size_ml}ml Sticlă Completă"


def sql_quote(s):
    """Escape a string for PostgreSQL single-quoted literal."""
    return "'" + s.replace("'", "''") + "'"


def main():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        products = json.load(f)

    # Deterministic UUID namespace so re-runs produce the same ids.
    NS = uuid.UUID("a8d38f1a-6e2b-4b0e-9d39-9b9f7f8c1c5e")

    lines = []
    lines.append("-- 006_full_pricelist_import.sql")
    lines.append("-- Generated by scripts/generate-import-sql.py from scripts/parsed-products.json")
    lines.append(f"-- Source: price_list copy.docx → {len(products)} products across "
                 f"{len({p['brand'] for p in products})} brands")
    lines.append("-- Idempotent: re-running this script will not duplicate rows.")
    lines.append("-- Stock defaults to 1 per SKU.")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")

    total_skus = 0
    for p in products:
        brand = p["brand"]
        name = p["name"]
        skus = p.get("skus", [])
        if not skus:
            continue

        product_id = str(uuid.uuid5(NS, f"{brand}::{name}"))

        b = sql_quote(brand)
        n = sql_quote(name)
        pid = sql_quote(product_id)

        lines.append(f"-- {brand} :: {name}")
        # Match the DB's case-insensitive unique constraint:
        # UNIQUE (lower(trim(brand)), lower(trim(name)))
        match_sql = (
            f"lower(trim(brand)) = lower(trim({b})) AND "
            f"lower(trim(name)) = lower(trim({n}))"
        )
        match_sql_p = (
            f"lower(trim(p.brand)) = lower(trim({b})) AND "
            f"lower(trim(p.name)) = lower(trim({n}))"
        )

        lines.append(
            "INSERT INTO products "
            "(id, brand, name, description, image_url, notes_top, notes_mid, notes_base, "
            "concentration, family, gender_neutral, launch_year, rating, review_count, stock_volume) "
            f"SELECT {pid}::uuid, {b}, {n}, '', '', "
            "ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], "
            "'', '', true, 0, 0, 0, 1 "
            f"WHERE NOT EXISTS (SELECT 1 FROM products WHERE {match_sql});"
        )

        for sku in skus:
            size_ml = sku["size_ml"]
            price = sku["price_bani"]
            label = label_for(size_ml)
            sku_id = str(uuid.uuid5(NS, f"{brand}::{name}::{size_ml}"))
            sid = sql_quote(sku_id)
            lab = sql_quote(label)
            # 1. Update existing SKU row (if any) with the new price + stock + label.
            lines.append(
                f"UPDATE skus SET price = {price}, stock = 1, label = {lab}, updated_at = now() "
                f"WHERE size_ml = {size_ml} AND product_id IN ("
                f"SELECT id FROM products WHERE {match_sql});"
            )
            # 2. Insert if no row yet for this (product, size).
            lines.append(
                "INSERT INTO skus (id, product_id, size_ml, price, stock, label) "
                f"SELECT {sid}::uuid, p.id, {size_ml}, {price}, 1, {lab} "
                f"FROM products p WHERE {match_sql_p} "
                f"  AND NOT EXISTS (SELECT 1 FROM skus s WHERE s.product_id = p.id AND s.size_ml = {size_ml});"
            )
            total_skus += 1
        lines.append("")

    lines.append("COMMIT;")
    lines.append("")
    lines.append(f"-- {len(products)} products, {total_skus} SKUs total.")

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"wrote {OUT_PATH}: {len(products)} products, {total_skus} SKUs")


if __name__ == "__main__":
    main()
